apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ugoasoluka/Aloha-review
    targetRevision: HEAD
    path: argocd/root
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd/root
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ugoasoluka/Aloha-review
    targetRevision: HEAD
    path: "argocd/external-dns"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "external-dns"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ugoasoluka/Aloha-review
    targetRevision: HEAD
    path: "argocd/lb-controller"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "kube-system"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasky
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ugoasoluka/Aloha-review
    targetRevision: HEAD
    path: "argocd/tasky-chart"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "tasky"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
