apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tasky-mongo
  namespace: tasky
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tasky-app-secrets
    kind: ClusterSecretStore
  target:
    name: tasky-mongo-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: tasky-app-secrets        
        property: MONGODB_URI
    - secretKey: SECRET_KEY
      remoteRef:
        key: tasky-app-secrets        
        property: SECRET_KEY                    