apiVersion: v2
name: external-dns
description: External DNS Helm chart for Kubernetes
version: 1.16.0
appVersion: 0.16.1
dependencies:
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.16.0
