# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: aws-lb-controller
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: "https://aws.github.io/eks-charts"
#     chart: "aws-load-balancer-controller"
#     targetRevision: "1.12.0 "
#     helm:
#       releaseName: "aws-load-balancer-controller"
#       valueFiles:
#         - argocd/lb-controller/lb-values.yaml
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: "kube-system"
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true

apiVersion: v2
name: aws-load-balancer-controller
description: AWS Load Balancer Controller Helm chart for Kubernetes
version: 1.12.0
appVersion: v2.12.0
dependencies:
  - name: aws-load-balancer-controller
    repository: "https://aws.github.io/eks-charts"
    version: 1.12.0
